apiVersion: apps/v1
kind: Deployment
metadata:
  name: recording-deployment
  labels:
    app: recording
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recording
  template:
    metadata:
      labels:
        app: recording
    spec:
      imagePullSecrets:
        - name: ghcr-credentials #  create secret before apply
      containers:
        - name: recording-container
          image: ghcr.io/achilleas2942/cnmpc-recording:latest
          resources:
          command: ["/bin/bash", "-c", "./root/catkin_ws/src/cnmpc_recording/src/run_k8s_resource_metrics.sh"]
          env:
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ROS_MASTER_URI
              value: "http://roscore:11311"
